/**
 * Where the Prisma client comes from — Cloudflare Workers build.
 *
 * Generated by the `workersClient` generator in prisma/schema.prisma. It loads
 * its query compiler with `import("./query_compiler_bg.wasm?module")`, which
 * Wrangler bundles natively, instead of reading the file off a disk that does
 * not exist on Workers.
 *
 * next.config.mjs aliases prisma-client.ts to this file when CF_WORKERS=1.
 * Nothing should import it directly — doing so would break `next dev`, the
 * seed and the integration tests, all of which run under Node.
 */
export { Prisma, PrismaClient } from '@/generated/prisma/client';
